@startuml

package "strongest-todo" {

  class StrongestTodoViewModel {
      - todos:StrongestTodo
      + addTodo()
  }

  class StrongestTodo {
      + todoList:KnockoutObservableArray<Todo>
      + void add(content:string)
      + void delete(target:Todo)
  }

  class Todo {
    + content:string
    + done:boolean
  }

  StrongestTodo "1" o- "0..*" Todo : "集約"
  StrongestTodoViewModel "1" o- "1" StrongestTodo : "保持"

}

@enduml
