@startuml

package "strongest-todo" {

  class StrongestTodo {
      + todoList:KnockoutObservableArray<Todo>
      + void add(content:string)
  }

  class Todo {
    + content:string
    + check:boolean
  }

  StrongestTodo "1" o- "0..*" Todo : "集約"

}

@enduml
